import requests, json
import json
import random
import time
import uuid
from datetime import datetime




def create_random_task():
    dt= datetime.now()
    t1 = dt.strftime('%Y-%m-%dT%H:%M:%S')
    # Create a task but without task_id because the post module generates that
    # automatically.
    x = json.dumps({          
    "title": "empty",
    "board": "Backlog", 
    "from_unit": uuid.uuid4().hex , 
    "to_unit": uuid.uuid4().hex , 
    "command": {
        "announce": "blank"
        }, 
    "response": {
        "blank": "blank"
        }
    })
    
#     x = {
#     "task_id": uuid.uuid4().hex ,
#     "board": "Backlog", 
#     "from_unit": uuid.uuid4().hex , 
#     "to_unit": uuid.uuid4().hex , 
#     "create_time": t1, 
#     "start_time":  t1, 
#     "complete_time":  t1, 
#     "expires_time":  t1, 
#     "command": {
#         "announce": "nlanl"
#         }, 
#     "response": {
#         "blank": "blank"
#         }
#     }
        
    return json.loads(x)

def get_task(task_id):
    t = task_id.replace("-", "")

    getURL = "http://127.0.0.1:8000/api/tasks/task_id/"+t

    r = requests.get(getURL,
                     data={},
                     headers={"Accept": "application/json"},
                     cookies=None,
                     auth=None)
    r.raise_for_status()
    return json.loads(r.content)

def post_task(task):
    # Take a dict task
    postURL = "http://127.0.0.1:8000/api/tasks/"
    # Task_id is authomatically generated by task board
    # Remove it
    postData = json.dumps({
    "title": task['title'], 
    "board": task['board'], 
    "from_unit": task['from_unit'], 
    "to_unit": task['to_unit'], 
    "command": task['command'], 
    "response": task['response']
    })   
    


    response = requests.post(url=postURL,
                     data=postData,
                     headers={"Content-Type": "application/json"},
                     cookies=None,
                     auth=None)
    
    response.raise_for_status()

    return json.loads(response.content)

def patch_task(task_id, json_package):

    
    postURL = "http://127.0.0.1:8000/api/tasks/task_id/" + task_id
    Data = json.dumps(json_package)



    response = requests.patch(url=postURL,
                     data=Data,
                     headers={"Content-Type": "application/json"},
                     cookies=None,
                     auth=None)

    response.raise_for_status()
    
    return json.loads(response.content)

def get_new_tasks(unit_id):
    u = unit_id.replace("-", "")
    getURL = "http://127.0.0.1:8000/api/tasks/to_unit/"+ u + "/?board=Backlog"
   
    response = requests.get(getURL,
                     data={},
                     headers={"Accept": "application/json"},
                     cookies=None,
                     auth=None)
    response.raise_for_status()

    return json.loads(response.content)

if __name__ == "__main__":
    pass
